### ISSUE TITLE
페이스북 연동 / 연동 해지 후 토큰 업데이트

### ISSUE THREAD

**Issue by bekker** [wafflestudio/snutt-webclient#11]
페이스북 연동 / 연동 해지 후 토큰 업데이트가 되지 않아,
로그아웃 하기 전까지 잘못된 user token이라는 메세지가 지속적으로 발생 및 서비스 이용 불가

**Comment by zxzl** [comment]
데브서버에서 http://dev.api.snutt.kr/v1/user/account 로 요청을 날리면 학교에서 http://147.46.79.10/waf/deny02.html 이리로 redirect 시켜줌.. ㅜㅜ

**Comment by zxzl** [comment]
딱 1년 지나서 다시 보는 중..

**Comment by zxzl** [comment]
- [ ] 페북 로그인 -> 계정 삭제 케이스 만들기
- [ ] 로컬 로그인 -> 페북 연동 -> 페북 해지 케이스 만들기
- [ ] 로컬 로그인 -> 페북 연동 -> 계정 삭제 케이스 만들기
- [ ] 탈퇴하고 나서 임시 토큰을 발급 받아오도록 고치기
