### ISSUE TITLE
리포 컴파일 실패

### ISSUE THREAD

**Issue by palindrom615** [wafflestudio/snutt-webclient#47]
```
Failed to compile.

./src/actions/loadingActions.js
Module not found: Can't resolve 'actions/actionTypes' in 'C:\Users\jwm\Projects\snutt-webclient\src\actions'
```

https://github.com/wafflestudio/snutt-webclient/blob/ff1baeab83ee707dbecebd973491000b8d81da4d/src/actions/loadingActions.js#L10
등과 같은 소스 파일을 보면 `src`에 있는 코드를 절대경로로 import해서 컴파일이 실패합니다. 

[webpack resolve.alias](https://webpack.js.org/configuration/resolve/) 설정이 아무데도 안되어 있는데 이게 컴파일이 되나요?

아니면 뭔가 제가 모르는 부트스트랩 코드가 있나요? 빌드 환경은 windows 10 node 12.9.1입니다.

**Comment by zxzl** [comment]
안녕하세요, `.env.example`에 따라서 `.env`를 넣어주시면 컴파일이 됩니다
https://github.com/wafflestudio/snutt-webclient#usage
